wallpaper {
    monitor = HDMI-A-1
    path =  /home/anthony/Pictures/4k-Wallpapers/Monochrome/black-waves-2.jpg     # ← change this
    fit_mode = cover                       # options: cover, contain, fill, tile
}

wallpaper {
    monitor = DVI-D-1
    path = /home/anthony/Pictures/4k-Wallpapers/Vertical/gustavdore-2.jpg
     # same or different image
    fit_mode = cover
}

# Optional: fallback for any other monitor
wallpaper {
    monitor = 
    path = /home/anthony/Pictures/4k-Wallpapers/Monochrome/black-waves-2.jpg
    fit_mode = cover
}
