backend = "glx";

blur-method = "dual_kawase";
blur-strength = 7;
blur-background = true;

# prevent tearing/glitching
glx-copy-async = false;
use-damage = false;

opacity-rule = [
  "88:class_g = 'kitty' && focused",
  "83:class_g = 'kitty' && !focused",
  "88:class_g = 'Thunar' && focused",
  "83:class_g = 'Thunar' && !focused",
  "97:class_g = 'Obsidian' && focused",
  "94:class_g = 'Obsidian' && !focused",
];
